### ISSUE TITLE
 Do you have any plans to publish technical reports or papers describing the principles of your improvements?

### ISSUE THREAD

**Issue by wangqiang9** [FireRedTeam/DynamicPose#2]
Very interesting work! Do you have any plans to publish technical reports or papers describing the principles of your improvements? I'm looking forward to it.

**Comment by dynamic-X-LAB** [comment]
> Very interesting work! Do you have any plans to publish technical reports or papers describing the principles of your improvements? I'm looking forward to it.

Thank you for your interest. This work is primarily based on the AnimateAnyone framework, with some additional engineering, data collection, and cleaning efforts. It's not particularly suitable for publishing a paper. If we have extra bandwidth, we might consider releasing a report. We have another project called PhotoPoster, which is an image-based human animation system. There is a report available at https://photo-poster.github.io/ that you can refer to.
