### ISSUE TITLE
Given groups=1, weight of size [17, 1280, 7, 7], expected input[1, 1310, 12, 9] to have 1280 channels, but got 1310 channels instead

### ISSUE THREAD

**Issue by leeooo001** [FireRedTeam/DynamicPose#3]
site-packages\torch\nn\modules\conv.py", line 455, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride, self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [17, 1280, 7, 7], expected input[1, 1310, 12, 9] to have 1280 channels, but got 1310 channels instead
你好, 预处理图像时，出现了这个错误，请问你知道是什么原因么？
我的mmcv-2.1.0, mmdet-3.2.0,mmebgube-0.10.4,mmpose-1.3.2,
卡在video2pose.py 403行 body = next(body)['predictions'][0][0]

ps: 好像是那个rtmpose-x模型的问题，我使用rtmpose-l模型就没问题了

**Comment by dynamic-X-LAB** [comment]
> site-packages\torch\nn\modules\conv.py", line 455, in _conv_forward return F.conv2d(input, weight, bias, self.stride, self.padding, self.dilation, self.groups) RuntimeError: Given groups=1, weight of size [17, 1280, 7, 7], expected input[1, 1310, 12, 9] to have 1280 channels, but got 1310 channels instead 你好, 预处理图像时，出现了这个错误，请问你知道是什么原因么？ 我的mmcv-2.1.0, mmdet-3.2.0,mmebgube-0.10.4,mmpose-1.3.2, 卡在video2pose.py 403行 body = next(body)['predictions'][0][0]
> 
> ps: 好像是那个rtmpose-x模型的问题，我使用rtmpose-l模型就没问题了

We have not encountered this issue. If it's just for prediction, you can choose to use the simpler dwpose or rtmpose-l.
To provide additional context on why we adopted so many models:
We utilized several models to ensure that the pose points are sufficiently precise and robust, primarily to guarantee the accuracy of the training data. For the body, we used rtmpose-x, which has the highest Whole AP (Average Precision) for body poses, but it doesn't include hand points. For the hands, we used rtmw-x, which includes fine points for hand details, although its foot points are often significantly off. For the feet, we used the more robust dwpose. These more precise pose points have led to a noticeable improvement in the training of the model.

**Comment by leeooo001** [comment]
thanks.
